---
title: "projekt 2"
author: "Damian Wysokiński"
date: "12 12 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(stringsAsFactors=FALSE)

library(sqldf)
library(dplyr)
library(data.table)
#install.packages('R.utils')

```

Wczytanie danych
```{r}

# to data.frames
Badges <- read.csv("travel_stackexchange_com/Badges.csv.gz")
Comments <- read.csv("travel_stackexchange_com/Comments.csv.gz")
PostLinks <- read.csv("travel_stackexchange_com/PostLinks.csv.gz")
Posts <- read.csv("travel_stackexchange_com/Posts.csv.gz")
Tags <- read.csv("travel_stackexchange_com/Tags.csv.gz")
Users <- read.csv("travel_stackexchange_com/Users.csv.gz")
Votes <- read.csv("travel_stackexchange_com/Votes.csv.gz")

# to data.tables
Badges_dt <- fread("travel_stackexchange_com/Badges.csv.gz")
Comments_dt <- fread("travel_stackexchange_com/Comments.csv.gz")
PostLinks_dt <- fread("travel_stackexchange_com/PostLinks.csv.gz")
Posts_dt <- fread("travel_stackexchange_com/Posts.csv.gz")
Tags_dt <- fread("travel_stackexchange_com/Tags.csv.gz")
Users_dt <- fread("travel_stackexchange_com/Users.csv.gz")
Votes_dt <- fread("travel_stackexchange_com/Votes.csv.gz")
```

Wykonane zadania
```{r}
wersja_dyplr <- c('T','N','T','T','N')
wersja_f_bazowe <- c('N','N','N','N','N')
wersja_data_table <- c('T','N','N','N','N')
row_nr <- 1:5
data.frame(row_nr, wersja_dyplr, wersja_f_bazowe, wersja_data_table)
```

Zad1
```{r}
# SQL
zad1_sql <- sqldf('SELECT Posts.Title, RelatedTab.NumLinks
FROM
  (SELECT RelatedPostId AS PostId, COUNT(*) AS NumLinks
  FROM PostLinks
  GROUP BY RelatedPostId) AS RelatedTab
JOIN Posts ON RelatedTab.PostId=Posts.Id
WHERE Posts.PostTypeId=1
ORDER BY NumLinks DESC
')

zad1_sql
```

```{r}
#zad 1 wewnetrzna wartosc

RelatedTab_zad_1_sql <- sqldf('SELECT RelatedPostId AS PostId, COUNT(*) AS NumLinks
  FROM PostLinks
  GROUP BY RelatedPostId 
')
 
RelatedTab_zad_1_sql
```
zad 1 dplyr
```{r}
# RelatedTab_zad_1_sql 
PostLinks 

RelatedTab <- PostLinks %>%
  group_by(RelatedPostId) %>%
  summarise(NumLinks = n()) %>% 
  rename(PostId = RelatedPostId)

all_equal(RelatedTab, RelatedTab_zad_1_sql)

zad1_dplyr <- inner_join(RelatedTab,Posts, by = c("PostId" = "Id")) %>% 
  filter(PostTypeId == 1) %>% 
  select(Title, NumLinks) %>% 
  arrange(desc(NumLinks))

all_equal(zad1_dplyr, zad1_sql)
```
Zad 1 data.table
```{r}
related_table_dt <- PostLinks_dt[, .(NumLinks = .N), by = RelatedPostId] %>% setnames(old = "RelatedPostId", new = "PostId")
related_table_dt

all_equal(RelatedTab_zad_1_sql, related_table_dt) # do tego miejsca jest tak samo
#################################
zad1_sql_bez_where <- sqldf('SELECT Posts.Title, RelatedTab.NumLinks
FROM
  (SELECT RelatedPostId AS PostId, COUNT(*) AS NumLinks
  FROM PostLinks
  GROUP BY RelatedPostId) AS RelatedTab
JOIN Posts ON RelatedTab.PostId=Posts.Id
ORDER BY NumLinks, Title')


merged <- merge(related_table_dt, Posts_dt, by.x = "PostId", by.y = "Id")
keycol <- c("NumLinks")
merged <- setorderv(merged, keycol, c(-1))
merged <- merged[PostTypeId == 1, c("Title", "NumLinks")]
merged$Title <- gsub('""','"',merged$Title) # data.table zamiast "..." tworzy ""..."" wiec trzeba zamienic podwojne "" na pojedyncze "

all_equal(merged, zad1_sql)               
```





Zad 2 sql
```{r}
zad2_sql <- sqldf(
'SELECT
  Users.DisplayName,
  Users.Age,
  Users.Location,
  SUM(Posts.FavoriteCount) AS FavoriteTotal,
  Posts.Title AS MostFavoriteQuestion,
  MAX(Posts.FavoriteCount) AS MostFavoriteQuestionLikes
FROM Posts
JOIN Users ON Users.Id=Posts.OwnerUserId
WHERE Posts.PostTypeId=1
GROUP BY OwnerUserId
ORDER BY FavoriteTotal DESC
LIMIT 10
')
head(zad2_sql)
```
Zad 2 dplyr
```{r}

# bledne rozwiazanie - wielokrotnie pojawia sie MostFaviouteQuestion dla nawego Favourite Count
users_inner <- Users %>% select(DisplayName, Age, Location, Id)

inner_join(Posts, Users, by = c("OwnerUserId" = "Id")) %>% 
  filter(PostTypeId == 1, !is.na(FavoriteCount)) %>% 
  group_by(OwnerUserId) %>%
  #summarise(FavoriteTotal = sum(FavoriteCount), MostFavoriteQuestionLikes = max(FavoriteCount)) %>% 
  summarise(DisplayName, Age, Location, FavoriteTotal = sum(FavoriteCount), MostFavoriteQuestion = Title, MostFavoriteQuestionLikes = max(FavoriteCount)) %>%
  #inner_join(users_inner, by = c("OwnerUserId" = "Id")) %>%
  ungroup() %>%
  select(DisplayName, Age, Location, FavoriteTotal, MostFavoriteQuestion, MostFavoriteQuestionLikes) %>% 
  arrange(desc(FavoriteTotal)) %>% 
  top_n(10)
  
  #rename(MostFavoriteQuestion = Title)

```
Zad 3

Zad3 SQL
```{r}
zad3_sql <- sqldf("
SELECT
  Posts.Title,
  CmtTotScr.CommentsTotalScore
FROM (
    SELECT
      PostID,
      UserID,
      SUM(Score) AS CommentsTotalScore
    FROM Comments
    GROUP BY PostID, UserID
) AS CmtTotScr
JOIN Posts ON Posts.ID=CmtTotScr.PostID AND Posts.OwnerUserId=CmtTotScr.UserID
WHERE Posts.PostTypeId=1
ORDER BY CmtTotScr.CommentsTotalScore DESC
LIMIT 10")
zad3_sql
```
zad3 dyplyr
```{r}
CmtTotScr_sql <- sqldf('SELECT
PostID,
UserID,
SUM(Score) AS CommentsTotalScore
FROM Comments
GROUP BY PostID, UserID')

(CmtTotScr <- Comments %>% 
  group_by(PostId, UserId) %>% 
  summarise(CommentsTotalScore = sum(Score)))

all_equal(CmtTotScr, CmtTotScr_sql)

zad3_dyplr <- inner_join(CmtTotScr, Posts, by = c("PostId"="Id", "UserId"="OwnerUserId")) %>% 
  filter(PostTypeId == 1) %>% 
  arrange(desc(CommentsTotalScore)) %>%
  ungroup() %>% 
  select(Title, CommentsTotalScore) %>% 
  top_n(10)

all_equal(zad3_dyplr, zad3_sql)
```

Zad4

zad4 sql
```{r}
zad4_sql <- sqldf('
SELECT DISTINCT
  Users.Id,
  Users.DisplayName,
  Users.Reputation,
  Users.Age,
  Users.Location
FROM (
      SELECT
        Name, UserID
      FROM Badges
      WHERE Name IN (
        SELECT
          Name
        FROM Badges
        WHERE Class=1
        GROUP BY Name
        HAVING COUNT(*) BETWEEN 2 AND 10
      )
    AND Class=1
  ) AS ValuableBadges
JOIN Users ON ValuableBadges.UserId=Users.Id
')
zad4_sql
```
zad4_dyplr
```{r}
(inner_names_sql <- sqldf('
SELECT
Name
FROM Badges
WHERE Class=1
GROUP BY Name
HAVING COUNT(*) BETWEEN 2 AND 10'))

(inner_names <- Badges %>% 
  filter(Class == 1) %>% 
  group_by(Name) %>% 
  summarise(cnt = n()) %>% 
  ungroup() %>% 
  filter(cnt >= 2, cnt <= 10) %>% 
  select(Name) %>%
    pull()) #pull potrzebny do kolejnego zapytania (gdzie uzywa sie %in%s)
#all_equal(inner_names_sql, inner_names)


(ValuableBadges_sql <- sqldf('
SELECT
Name, UserID
FROM Badges
WHERE Name IN (
    SELECT
      Name
    FROM Badges
    WHERE Class=1
    GROUP BY Name
    HAVING COUNT(*) BETWEEN 2 AND 10
)
AND Class=1
'))

(ValuableBadges <- Badges %>% 
  filter(Name %in% inner_names, Class == 1) %>% 
  select(Name, UserId))

all_equal(ValuableBadges, ValuableBadges_sql)

zad4_dyplr <- inner_join(ValuableBadges, Users, by = c("UserId" = "Id")) %>% 
    rename(Id = UserId) %>% 
    select(Id, DisplayName, Reputation, Age, Location) %>% 
  distinct

all_equal(zad4_dyplr, zad4_sql)
  
```
Zad 5

zad5_sql
```{r}
(zad_sql <- sqldf('
SELECT
    Questions.Id,
    Questions.Title,
    BestAnswers.MaxScore,
    Posts.Score AS AcceptedScore,
    BestAnswers.MaxScore-Posts.Score AS Difference
FROM (
        SELECT Id, ParentId, MAX(Score) AS MaxScore
        FROM Posts
        WHERE PostTypeId==2
        GROUP BY ParentId
) AS BestAnswers
JOIN (
      SELECT * FROM Posts
      WHERE PostTypeId==1
    ) AS Questions
  ON Questions.Id=BestAnswers.ParentId
JOIN Posts ON Questions.AcceptedAnswerId=Posts.Id
WHERE Difference>50
ORDER BY Difference DESC
'))

best_answers_sql <- sqldf(
'SELECT Id, ParentId, MAX(Score) AS MaxScore
FROM Posts
WHERE PostTypeId==2
GROUP BY ParentId')

best_answers <- Posts %>% 
  filter(PostTypeId == 2) %>% 
  group_by(ParentId) %>% 
  summarise(MaxScore = max(Score))



```

```{r}
Posts %>% filter(ParentId <=3) %>% select(Id, ParentId) %>% arrange(ParentId)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
